version: '3.8'
services:
  openvoice_app:
    image: chatterbox-model
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatterbox-model
    volumes:
      - "~/Documents/Docker/chatterbox:/app/output"
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]