version: '3.8'
services:
  openvoice_app:
    image: chatterbox-enchanced
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatterbox-enchanced
    volumes:
      - "~/Documents/Docker/chatterbox-enchanced:/app/output"
      - ".:/app"
    ports:
      - "7861:7861"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]